web:
  build: .
  command: "bash -c 'App --env=production --workdir=/app/'"
  working_dir: /app/
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
